name: dataset-dtm
channels:
  - conda-forge
dependencies:
  - python=3.10
  - numpy
  - pandas
  - scikit-learn
  - joblib
  - pyproj
  - networkx
  - laspy
  - lazrs-python
  - pdal
  - rasterio
  - geopandas
  - shapely
  - fiona
  - jupyter
  - matplotlib
